from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import sqlite3
import pandas as pd
import os
from datetime import datetime

app = Flask(__name__)
CORS(app)
DB_PATH = "flights.db"

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

from flask import send_from_directory

@app.route("/")
def index():
    # Serve the original master dashboard generated by analyzer.py
    return send_from_directory(".", "dashboard.html")

@app.route("/calendar")
def calendar():
    # Serve the interactive calendar UI module
    return render_template("dashboard.html")

@app.route("/api/routes")
def get_routes():
    conn = get_db_connection()
    routes = conn.execute("SELECT DISTINCT route FROM flight_prices ORDER BY route").fetchall()
    conn.close()
    return jsonify([row["route"] for row in routes])

@app.route("/api/calendar")
def get_calendar():
    route = request.args.get("route")
    month_prefix = request.args.get("month") # e.g., "2026-04"
    
    if not route or not month_prefix:
        return jsonify({"error": "Missing route or month parameter"}), 400
        
    conn = get_db_connection()
    
    # Get the latest scrape for each day to show the most current calendar prices
    query = """
    WITH RankedPrices AS (
        SELECT flight_date, price, scrape_datetime,
               row_number() OVER (PARTITION BY flight_date ORDER BY scrape_datetime DESC) as rn
        FROM flight_prices
        WHERE route = ? AND flight_date LIKE ?
    )
    SELECT flight_date, price
    FROM RankedPrices
    WHERE rn = 1
    ORDER BY flight_date
    """
    
    rows = conn.execute(query, (route, f"{month_prefix}%")).fetchall()
    conn.close()
    
    data = {row["flight_date"]: row["price"] for row in rows}
    return jsonify(data)

@app.route("/api/flights")
def get_flights():
    route = request.args.get("route")
    date = request.args.get("date")
    
    if not route or not date:
        return jsonify({"error": "Missing route or date parameter"}), 400
        
    conn = get_db_connection()
    
    query = """
    WITH FirstLastScrapes AS (
        SELECT 
            flight_number, 
            departure_time, 
            arrival_time, 
            price, 
            is_special,
            scrape_datetime,
            row_number() OVER (PARTITION BY flight_number ORDER BY scrape_datetime DESC) as rn_desc,
            row_number() OVER (PARTITION BY flight_number ORDER BY scrape_datetime ASC) as rn_asc
        FROM flight_details
        WHERE route = ? AND flight_date = ?
    ),
    LatestFlights AS (
        SELECT * FROM FirstLastScrapes WHERE rn_desc = 1
    ),
    FirstFlights AS (
        SELECT * FROM FirstLastScrapes WHERE rn_asc = 1
    )
    SELECT 
        l.flight_number, 
        l.departure_time, 
        l.arrival_time, 
        l.price as latest_price, 
        l.is_special,
        f.price as first_price,
        (l.price - f.price) as price_change,
        l.scrape_datetime
    FROM LatestFlights l
    LEFT JOIN FirstFlights f ON l.flight_number = f.flight_number
    ORDER BY l.price ASC, l.departure_time ASC
    """
    
    rows = conn.execute(query, (route, date)).fetchall()
    conn.close()
    
    return jsonify([dict(row) for row in rows])

@app.route("/api/flight-history")
def get_flight_history():
    route = request.args.get("route")
    date = request.args.get("date")
    flight_number = request.args.get("flight")
    
    if not route or not date or not flight_number:
        return jsonify({"error": "Missing parameters"}), 400
        
    conn = get_db_connection()
    
    query = """
    SELECT scrape_datetime, price
    FROM flight_details
    WHERE route = ? AND flight_date = ? AND flight_number = ?
    ORDER BY scrape_datetime ASC
    """
    
    rows = conn.execute(query, (route, date, flight_number)).fetchall()
    conn.close()
    
    history = [
        {"x": row["scrape_datetime"], "y": row["price"]} 
        for row in rows
    ]
    
    return jsonify(history)

from flask import send_from_directory

import json

def get_booking_advice(days_until, routes=None):
    """Generate human-readable booking advice."""
    if days_until < 0:
        return "This date has already passed."
    if days_until == 0:
        return "This flight is today! Book immediately if seats are available."
    if days_until <= 2:
        return "Very short notice — prices are likely at their highest. Book only if you must travel."

    # Check if prices are dropping
    if routes:
        dropping = [r for r in routes if r.get("trend") == "dropping"]
        rising = [r for r in routes if r.get("trend") == "rising"]
        if dropping and not rising:
            return f"Prices are DROPPING — consider waiting a bit longer for a better deal. You have {days_until} days."
        if rising and not dropping:
            return f"Prices are RISING — book NOW before they go higher! {days_until} days until flight."

    if days_until > 90:
        return f"You have {days_until} days — plenty of time. Prices tend to be lowest 2-3 months before. Monitor and book when you see a dip."
    if days_until > 30:
        return f"You have {days_until} days — good window. Watch for price drops and book within the next few weeks."
    if days_until > 14:
        return f"{days_until} days left — prices may start rising soon. Consider booking this week."
    if days_until > 7:
        return f"Only {days_until} days left — book soon! Prices typically increase in the last week."
    return f"Only {days_until} days away — book NOW for the best remaining price."

@app.route("/api/flight-advice")
def flight_advice():
    """Analyze collected data to give booking advice for a specific flight date."""
    flight_date_str = request.args.get("date")
    if not flight_date_str:
        return jsonify({"error": "Missing date parameter"}), 400

    try:
        conn = get_db_connection()

        # Get all price records for this flight date
        rows = conn.execute("""
            SELECT route, price, scrape_datetime, days_before_flight
            FROM flight_prices
            WHERE flight_date = ?
            ORDER BY scrape_datetime
        """, (flight_date_str,)).fetchall()

        if not rows:
            # No exact data — use pattern-based advice from similar days
            flight_date = datetime.strptime(flight_date_str, "%Y-%m-%d")
            day_of_week = flight_date.strftime("%A")
            days_until = (flight_date - datetime.now()).days

            # Get average price for similar days_before_flight range
            similar = conn.execute("""
                SELECT route, AVG(price) as avg_price, MIN(price) as min_price, COUNT(*) as samples
                FROM flight_prices
                WHERE days_before_flight BETWEEN ? AND ?
                GROUP BY route
            """, (max(0, days_until - 3), days_until + 3)).fetchall()

            conn.close()
            return jsonify({
                "date": flight_date_str,
                "day_of_week": day_of_week,
                "days_until": days_until,
                "has_data": False,
                "similar_prices": [
                    {"route": r["route"], "avg_price": round(r["avg_price"], 2),
                     "min_price": round(r["min_price"], 2), "samples": r["samples"]}
                    for r in similar
                ],
                "advice": get_booking_advice(days_until, routes=None)
            })

        # We have data for this exact date
        flight_date = datetime.strptime(flight_date_str, "%Y-%m-%d")
        day_of_week = flight_date.strftime("%A")
        days_until = (flight_date - datetime.now()).days

        # Current prices per route (latest scrape)
        route_prices = {}
        price_history = {}
        for r in rows:
            route = r["route"]
            price = r["price"]
            scrape_dt = r["scrape_datetime"]
            days_before = r["days_before_flight"]
            
            if route not in route_prices:
                route_prices[route] = []
                price_history[route] = []
            route_prices[route].append({"price": price, "scrape": scrape_dt, "days_before": days_before})
            price_history[route].append({"price": price, "scrape": scrape_dt})

        # Build route summary
        routes = []
        for route, entries in route_prices.items():
            prices = [e["price"] for e in entries]
            latest = entries[-1]
            first = entries[0]
            trend = "stable"
            if len(prices) > 1:
                if latest["price"] < first["price"]:
                    trend = "dropping"
                elif latest["price"] > first["price"]:
                    trend = "rising"

            routes.append({
                "route": route,
                "current_price": latest["price"],
                "lowest_seen": min(prices),
                "highest_seen": max(prices),
                "avg_price": round(sum(prices) / len(prices), 2),
                "checks": len(prices),
                "trend": trend,
                "history": price_history[route]
            })

        # Get overall booking window pattern
        best_windows = conn.execute("""
            SELECT days_before_flight, AVG(price) as avg_price
            FROM flight_prices
            WHERE days_before_flight > 0
            GROUP BY days_before_flight
            ORDER BY AVG(price)
            LIMIT 5
        """).fetchall()

        # Count unique scrape days (to know if day/hour data is meaningful)
        unique_scrape_days = conn.execute("SELECT COUNT(DISTINCT DATE(scrape_datetime)) FROM flight_prices").fetchone()[0]

        # Best day of week to book PER ROUTE
        route_book_days_raw = conn.execute("""
            SELECT route,
                CASE CAST(strftime('%w', scrape_datetime) AS INTEGER)
                    WHEN 0 THEN 'Sunday' WHEN 1 THEN 'Monday' WHEN 2 THEN 'Tuesday'
                    WHEN 3 THEN 'Wednesday' WHEN 4 THEN 'Thursday'
                    WHEN 5 THEN 'Friday' WHEN 6 THEN 'Saturday'
                END as book_day,
                AVG(price) as avg_price
            FROM flight_prices
            WHERE days_before_flight > 0
            GROUP BY route, book_day
            ORDER BY route, avg_price
        """).fetchall()
        
        route_book_days = {}
        for r in route_book_days_raw:
            route = r["route"]
            if route not in route_book_days:
                route_book_days[route] = []
            route_book_days[route].append({"day": r["book_day"], "avg_price": round(r["avg_price"], 2)})

        # Best hour of day to book PER ROUTE
        route_book_hours_raw = conn.execute("""
            SELECT route,
                CAST(strftime('%H', scrape_datetime) AS INTEGER) as book_hour,
                AVG(price) as avg_price
            FROM flight_prices
            WHERE days_before_flight > 0
            GROUP BY route, book_hour
            ORDER BY route, avg_price
        """).fetchall()
        
        route_book_hours = {}
        for r in route_book_hours_raw:
            route = r["route"]
            if route not in route_book_hours:
                route_book_hours[route] = []
            route_book_hours[route].append({"hour": f"{r['book_hour']:02d}:00", "avg_price": round(r["avg_price"], 2)})

        conn.close()

        return jsonify({
            "date": flight_date_str,
            "day_of_week": day_of_week,
            "days_until": days_until,
            "has_data": True,
            "routes": routes,
            "best_windows": [{"days": int(w["days_before_flight"]), "avg_price": round(w["avg_price"], 2)} for w in best_windows],
            "route_book_days": route_book_days,
            "route_book_hours": route_book_hours,
            "unique_scrape_days": unique_scrape_days,
            "advice": get_booking_advice(days_until, routes)
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/price-detail")
def price_detail():
    """Get details of when a route's min or max price was recorded."""
    route = request.args.get("route")
    price_type = request.args.get("type", "min")
    
    if not route:
        return jsonify({"error": "Missing route"}), 400
        
    try:
        conn = get_db_connection()
        
        # Find the target price
        agg = "MIN" if price_type == "min" else "MAX"
        target_price = conn.execute(f"SELECT {agg}(price) FROM flight_prices WHERE route = ?", (route,)).fetchone()[0]
        
        if target_price is None:
            conn.close()
            return jsonify({"error": "No data for this route"})

        # Get unique flight dates matching this price
        rows = conn.execute("""
            SELECT flight_date, 
                   MIN(scrape_datetime) as first_scrape,
                   MAX(scrape_datetime) as latest_scrape,
                   MIN(days_before_flight) as days_before_flight,
                   COUNT(*) as times_seen
            FROM flight_prices
            WHERE route = ? AND price = ?
            GROUP BY flight_date
            ORDER BY flight_date ASC
        """, (route, target_price)).fetchall()
        
        conn.close()

        day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        records = []
        total_occurrences = 0
        for r in rows:
            total_occurrences += r["times_seen"]
            flight_dt = datetime.strptime(r["flight_date"], "%Y-%m-%d")
            
            latest_str = r["latest_scrape"]
            latest_dt = datetime.strptime(latest_str, "%Y-%m-%d %H:%M:%S") if " " in latest_str else datetime.strptime(latest_str, "%Y-%m-%dT%H:%M:%S")
            
            first_str = r["first_scrape"]
            first_dt = datetime.strptime(first_str, "%Y-%m-%d %H:%M:%S") if " " in first_str else datetime.strptime(first_str, "%Y-%m-%dT%H:%M:%S")
            
            if r["times_seen"] == 1:
                scrape_desc = latest_dt.strftime("%b %d, %H:%M")
            else:
                scrape_desc = f"{first_dt.strftime('%b %d')} to {latest_dt.strftime('%b %d, %H:%M')} ({r['times_seen']} scans)"

            records.append({
                "flight_date": r["flight_date"],
                "flight_day": day_names[flight_dt.weekday()],
                "scrape_time": scrape_desc,
                "days_before": r["days_before_flight"]
            })

        return jsonify({
            "route": route,
            "type": price_type,
            "price": target_price,
            "occurrences": total_occurrences,
            "records": records[:10]  # Return top 10 dates
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/status")
def status():
    """Return whether the scraper is currently running."""
    try:
        with open("status.json", "r") as f:
            data = json.load(f)
            return jsonify(data)
    except FileNotFoundError:
        return jsonify({"running": False})

@app.route("/api/last-update")
def last_update():
    """Return the last modification time of flights.db to trigger frontend refreshes."""
    if os.path.exists(DB_PATH):
        mtime = os.path.getmtime(DB_PATH)
        return jsonify({"last_update": mtime})
    return jsonify({"last_update": 0})

@app.route("/<string:filename>")
def serve_static_html(filename):
    if filename.endswith('.html'):
        return send_from_directory(".", filename)
    return "Not Found", 404

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True, port=8080)
