CREATE TABLE IF NOT EXISTS public.flight_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route TEXT NOT NULL,
    flight_date DATE NOT NULL,
    departure_time TEXT NOT NULL,
    scrape_datetime TIMESTAMP NOT NULL,
    days_before_flight INTEGER NOT NULL,
    price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS public.flight_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route TEXT NOT NULL,
    flight_date DATE NOT NULL,
    flight_number TEXT NOT NULL,
    departure_time TEXT NOT NULL,
    arrival_time TEXT NOT NULL,
    price REAL NOT NULL,
    is_cheapest INTEGER DEFAULT 0,
    is_special INTEGER DEFAULT 0,
    scrape_datetime TIMESTAMP NOT NULL,
    days_before_flight INTEGER NOT NULL
);

-- Note: you might also want to set up Row Level Security (RLS) policies here later
